### ISSUE TITLE
where 语法无法正确处理 None 值

### ISSUE THREAD

**Issue by earlzo** [shanbay/sorator#41]
先附上代码
```Python
    def where(self, column, operator=Null(), value=None, boolean='and'):
        """
        Add a where clause to the query

        :param column: The column of the where clause, can also be a QueryBuilder instance for sub where
        :type column: str or QueryBuilder

        :param operator: The operator of the where clause
        :type operator: str

        :param value: The value of the where clause
        :type value: mixed

        :param boolean: The boolean of the where clause
        :type boolean: str

        :return: The current QueryBuilder instance
        :rtype: QueryBuilder
        """
        # If the column is an array, we will assume it is an array of key-value pairs
        # and can add them each as a where clause. We will maintain the boolean we
        # received when the method was called and pass it into the nested where.
        if isinstance(column, dict):
            nested = self.new_query()
            for key, value in column.items():
                nested.where(key, '=', value)

            return self.where_nested(nested, boolean)

        if isinstance(column, QueryBuilder):
            return self.where_nested(column, boolean)

        if isinstance(column, list):
            nested = self.new_query()
            for condition in column:
                if isinstance(condition, list) and len(condition) == 3:
                    nested.where(condition[0], condition[1], condition[2])
                else:
                    raise ArgumentError('Invalid conditions in where() clause')
            return self.where_nested(nested, boolean)
```

orator 在不显式指定操作符时默认为`=`, 并将 operator 参数当做 value, 为了支持这一默认行为还自定义了一个类型`Null`, 但为了实现这样的默认行为将导致一下问题出现.

当我们需要查询某个字段为`None`的记录时, 只能使用 `where('some_field', None)` 的形式, 如果使用  `where('some_field', '=', None)`, 将会使 value 变为 `=`, 导致结果出现错误, 由于这一实现贯穿了整个框架, 因此改动会很大, 只能先在实际使用时避免这个情况了.

本该照着参数写就应该正确的逻辑, 却因为为了少填那么一个参数名却导致出错, 原作者该拿去祭天啊.

当时设计的时候用 `def where(self, column, value=None, operator='=', boolean='and')`  不就结了么, 哎

**Comment by earlzo** [comment]
再附上一个例子
```python interpreter
>>> models.BookPage.where('sentence_json').get().items
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/orator/orm/builder.py", line 608, in where
    self._query.where(column, operator, value, boolean)
  File "/usr/local/lib/python3.6/site-packages/orator/query/builder.py", line 377, in where
    raise ArgumentError('Value must be provided')
orator.exceptions.ArgumentError: Value must be provided
>>> models.BookPage.where('sentence_json', None).get().items
[<app.models.course.BookPage object at 0x7f7ad3a9e9b0>]
>>> models.BookPage.where('sentence_json', '=', None).get().items
[]
```

**Comment by earlzo** [comment]
而且用`where('some_field', None)` IDE又会警告, 这不是逼死强迫症么
